#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

data = json.load(sys.stdin)
host = data.get("host", '')

# Setup environment for jitsi
config = {
  "JICOFO_COMPONENT_SECRET": "df4jdDf49d3!dfg356Df83&",
  "JICOFO_AUTH_PASSWORD": "df4jdDf49d3!dfg356Df83&",
  "JVB_AUTH_PASSWORD": "df4jdDf49d3!dfg356Df83&",
  "JIGASI_XMPP_PASSWORD": "df4jdDf49d3!dfg356Df83&",
  "JIBRI_RECORDER_PASSWORD": "df4jdDf49d3!dfg356Df83&",
  "JIBRI_XMPP_PASSWORD": "df4jdDf49d3!dfg356Df83&",
  "TZ": "UTC",
  "PUBLIC_URL": host,
  "ENABLE_LETSENCRYPT": "0",
  "ETHERPAD_TITLE": "Video Chat",
  "ETHERPAD_DEFAULT_PAD_TEXT": "Welcome to Web Chat!\\n\\n",
  "ETHERPAD_SKIN_NAME": "colibris",
  "ETHERPAD_SKIN_VARIANTS": "super-light-toolbar super-light-editor light-background full-width-editor",
  "ENABLE_AUTH": "0",
  "ENABLE_GUESTS": "1",
  "XMPP_DOMAIN": "meet.jitsi",
  "XMPP_SERVER": "xmpp.meet.jitsi",
  "XMPP_BOSH_URL_BASE": "http://xmpp.meet.jitsi:5280",
  "XMPP_AUTH_DOMAIN": "auth.meet.jitsi",
  "XMPP_MUC_DOMAIN": "muc.meet.jitsi",
  "XMPP_INTERNAL_MUC_DOMAIN": "internal-muc.meet.jitsi",
  "XMPP_GUEST_DOMAIN": "guest.meet.jitsi",
  "XMPP_MODULES": "",
  "XMPP_MUC_MODULES": "",
  "XMPP_INTERNAL_MUC_MODULES": "",
  "JVB_BREWERY_MUC": "jvbbrewery",
  "JVB_AUTH_USER": "jvb",
  "JVB_STUN_SERVERS": "meet-jit-si-turnrelay.jitsi.net:443",
  "JVB_PORT": "10000",
  "JVB_TCP_HARVESTER_DISABLED": "true",
  "JVB_TCP_PORT": "4443",
  "JVB_TCP_MAPPED_PORT": "4443",
  "JICOFO_AUTH_USER": "focus",
  "JIGASI_XMPP_USER": "jigasi",
  "JIGASI_BREWERY_MUC": "jigasibrewery",
  "JIGASI_PORT_MIN": "20000",
  "JIGASI_PORT_MAX": "20050",
  "ENABLE_RECORDING": "0",
  "MPP_RECORDER_DOMAIN": "recorder.meet.jitsi",
  "JIBRI_RECORDER_USER": "recorder",
  "JIBRI_RECORDING_DIR": "/config/recordings",
  "JIBRI_FINALIZE_RECORDING_SCRIPT_PATH": "/config/finalize.sh",
  "JIBRI_XMPP_USER": "jibri",
  "JIBRI_BREWERY_MUC": "jibribrewery",
  "JIBRI_PENDING_TIMEOUT": "90",
  "JIBRI_STRIP_DOMAIN_JID": "muc",
  "JIBRI_LOGS_DIR": "/config/logs",
  "DISABLE_HTTPS": "1"
# "NEXTCLOUD_TRUSTED_DOMAINS": host,
# "NEXTCLOUD_DOMAIN": data.get('domain', ''),
}
agent.write_envfile('jitsi.env', config)