#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

port = agent.read_envfile("jitsi.env")["JVB_PORT"] if os.path.exists("jitsi.env") else "10000"

agent.add_public_service(os.environ['MODULE_ID'], [
    port + "/udp", # RTP over UDP
], replace_ports=True)

# Ignore exit code
